# Generated by Django 2.0.2 on 2018-05-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180506_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
