# Generated by Django 2.0.2 on 2018-05-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180506_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
