# Generated by Django 2.0.2 on 2018-05-10 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180506_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avg_interest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='core.Item'),
        ),
        migrations.AlterField(
            model_name='user_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
