# Generated by Django 2.0.2 on 2018-05-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180510_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_item_log',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user_item_log',
            name='user',
        ),
        migrations.AddField(
            model_name='user_item_log',
            name='user_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.User_Item'),
            preserve_default=False,
        ),
    ]
