# Generated by Django 2.0.2 on 2018-05-12 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='Profile',
        ),
    ]
