# Generated by Django 2.0.2 on 2018-05-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180515_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglist',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
