# Generated by Django 2.0.2 on 2018-05-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
