# Generated by Django 2.0.2 on 2018-05-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='message',
            new_name='body',
        ),
    ]
