# Generated by Django 2.0.2 on 2018-05-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180518_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='body',
            new_name='message',
        ),
    ]
