# Generated by Django 2.0.2 on 2018-05-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20180518_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='interaction',
        ),
        migrations.AddField(
            model_name='update',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
