# Generated by Django 2.0.2 on 2018-05-20 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180519_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_item_log',
            name='user_item',
        ),
        migrations.AlterField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='taglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='core.Taglist'),
        ),
        migrations.DeleteModel(
            name='User_Item_Log',
        ),
    ]
