# Generated by Django 2.0.2 on 2018-05-25 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_auto_20180520_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('is_private', models.NullBooleanField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
