# Generated by Django 2.0.2 on 2018-05-26 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_update_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_User_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user_tags', to=settings.AUTH_USER_MODEL)),
                ('user_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Tag')),
            ],
        ),
    ]
