# Generated by Django 2.0.2 on 2018-05-27 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_favorite_user_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='taglist',
        ),
        migrations.AddField(
            model_name='following',
            name='user_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User_Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
