# Generated by Django 2.0.2 on 2018-05-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20180526_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglist',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='taglist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Taglist',
        ),
    ]
