# Generated by Django 2.0.2 on 2018-05-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180526_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_official',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
