# Generated by Django 2.0.2 on 2018-05-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_tag_is_official'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='is_main',
            new_name='is_visible',
        ),
    ]
