# Generated by Django 2.0.2 on 2018-06-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180601_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_official',
            field=models.BooleanField(default=0),
        ),
    ]
