# Generated by Django 2.0.2 on 2018-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20180620_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='was_new',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
